### ISSUE TITLE
errors with the "list" command

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#110]
```
c:\repos\berrybrew>build\berrybrew list

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at BerryBrew.Berrybrew.List()
   at BBConsole.bbconsole.Main(String[] args)

c:\repos\berrybrew>berrybrew list

Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: '5.24.2_64'  Key being added: '5.24.2_64'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at BerryBrew.Berrybrew.PerlGenerateObjects(Boolean importIntoObject)
   at BBConsole.bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
This may have been caused by outdated json files (particularly perls_custom.json):
```
c:\repos\berrybrew>build\berrybrew list
        5.26.2_64
        5.10.1_32
```
