### ISSUE TITLE
unhandled exception with "modules import" if modules dir doesn't exist

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#169]
```
c:\repos\berrybrew>berrybrew modules import
the 'modules' functionality is in beta. It's best to export from an
older version of Perl and import into a newer one. Even still the
import process may take quite some time to complete. Please report
any issues.


Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BerryBrew.Message.Say(String label)
   at BerryBrew.Berrybrew.ImportModules(String version)
   at berrybrew.Bbconsole.Main(String[] args)
```

Lets:

- dynamically create the `modules` directory if it doesn't exist on import, then proceed
- in `clean modules`, do nothing if dir doesn't exist
- in `clean modules`, if the dir does exist, iterate over files, leaving custom ones, do a check to ensure *only* files with `\d\.\d+\.\d+_\d+` have been removed which will indicate success

**Comment by stevieb9** [comment]
Fixed in v1.25
