### ISSUE TITLE
fetch 'help' isn't handled correctly

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#178]
'help' is being considered incorrectly.

```
c:\repos\berrybrew>build\berrybrew.exe fetch help

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BerryBrew.Message.Say(String label)
   at berrybrew.Bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
`fetch` doesn't even have 'help' :)

Verified that help works for all of the commands that do have sub commands
