### ISSUE TITLE
removing a custom version sometimes breaks

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#199]
The following one was auto-registered after a `berrybrew fetch` updated the available list:

```
c:\repos\berrybrew>berrybrew list
        5.30.0_64   [custom]

c:\repos\berrybrew>berrybrew remove 5.30.0_64
Successfully removed Strawberry Perl 5.30.0_64

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at BerryBrew.Berrybrew.JsonWrite(String type, List`1 data, Boolean fullList)
   at BerryBrew.Berrybrew.PerlRemove(String perlVersionToRemove)
   at berrybrew.Bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
This was caused by updating the `perls.json` with the auto-installer. There was no provision to auto-register the orphaned perls, therefore they were not created as C# objects.
