### ISSUE TITLE
Uncaught exception with 'berrybrew clean all` regarding 'modules'

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#202]
This occurred while doing a clean. The `C:\berrybrew\modules` has not been created.

```
c:\repos\berrybrew>berrybrew clean all

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\berrybrew\modules'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchO
ption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at BerryBrew.Berrybrew.CleanModules()
   at BerryBrew.Berrybrew.Clean(String subcmd)
   at berrybrew.Bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
It does NOT happen with `berrybrew clean module`

**Comment by stevieb9** [comment]
I'm wrong, it does. `help` specifies `module` instead of `modules` as the command, but `modules` is the proper command, and is too broken.
