### ISSUE TITLE
Uncaught exception when installing an unknown version

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#316]
```
C:\repos\berrybrew>build\berrybrew.exe install 5.10.1
IN DEV MODE

Unknown version of Perl

Use the available command to see what versions of Strawberry Perl are available

System.ArgumentException: Unknown version: 5.10.1_64
   at BerryBrew.Berrybrew.PerlResolveVersion(String version)
   at BerryBrew.Berrybrew.Install(String version)
   at berrybrew.Bbconsole.Main(String[] args)
```

**Comment by stevieb9** [comment]
Fixed in 1.38
