### ISSUE TITLE
Unhandled exception if instance download fails

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#63]
c:\repos\berrybrew>berrybrew install 5.10.1_32

    Downloading http://strawberryperl.com/download/5.10.1.5/strawberry-perl-5.10.1.5-portable.zip to       
    C:\berrybrew\temp\strawberry-perl-5.10.1.5-portable.zip

    Unhandled Exception: System.Net.WebException: The remote server returned an error: (404) Not Found.
       at System.Net.WebClient.DownloadFile(Uri address, String fileName)
       at BerryBrew.Berrybrew.Fetch(StrawberryPerl perl)
       at BerryBrew.Berrybrew.Install(String version)
       at BBConsole.bbconsole.Main(String[] args)`

**Comment by stevieb9** [comment]
Fixed in 1.16, will auto-close upon merge.

**Comment by stevieb9** [comment]
Accidentally pushed to master. Reopening, will close when 1.16 is merged
