### ISSUE TITLE
unhandled exception if 'fetch' tries to register existing instance name

### ISSUE THREAD

**Issue by stevieb9** [stevieb9/berrybrew#96]
When 5.26.1.1 came out, we had already installed 5.26.1.0. They both use the tag `5.26.1_64`, so there's a duplicate key error. (This is on `1.17`).

Need to check of that key exists, then rename the instance to possibly `legacy_5.26.1_64` or something.

```
c:\repos\berrybrew>build\berrybrew.exe fetch
Registering legacy Perl '5.26.1_64' as custom...Successfully registered 5.26.1_64

c:\repos\berrybrew>build\berrybrew available

Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: '5.26.1_64'  Key being added: '5.26.1_64'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at BerryBrew.Berrybrew.PerlGenerateObjects(Boolean importIntoObject)
   at BBConsole.bbconsole.Main(String[] args)](url)
```

**Comment by stevieb9** [comment]
Actually, this is caused by the `build` version using the same instance directory as the live version
